### ISSUE TITLE
Option to disable update checker

### ISSUE THREAD

**Issue by SlimeDog** [KP56/Fake-Players-Spigot-Plugin#1]
FakePlayers 1.4

We block (almost) all outbound network calls on our servers. In addition, we have our own automagical update checker. Please provide a configuration option to disable the update checker.

**Comment by KP56** [comment]
I will make sure to add this feature, when a new version comes out.

**Comment by SlimeDog** [comment]
Confirmed fixed in FakePlayers 1.5. Thanks.
