### ISSUE TITLE
CONSOLE ERROR AND WARN

### ISSUE THREAD

**Issue by Hazugg** [KP56/Fake-Players-Spigot-Plugin#5]
console error playerjoin and nextengine
console warn multiversion

As you will see in the images when generating the bot, this error appears

![image](https://user-images.githubusercontent.com/31551514/115905181-59ad2300-a42b-11eb-8119-adfdf3f49fe1.png)
![image](https://user-images.githubusercontent.com/31551514/115905252-75182e00-a42b-11eb-8c8c-073ec7250afb.png)

after a while i get this error and the server hangs and not

![image](https://user-images.githubusercontent.com/31551514/115907137-12746180-a42e-11eb-8982-11afd4e27abd.png)

**Comment by KP56** [comment]
Thank you for reporting this issue. It will be fixed, when the 1.7 update gets released (in less than a week).
